apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-343751
  namespace: rm-343751
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: blog-from-343751
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          averageUtilization: 50
          type: Utilization
